"""Fallback jobs when external APIs fail."""

MOCK_JOBS_RAW = [
    {
        "_source_portal": "Datos demo",
        "slug": "mock-helpdesk-zurich",
        "company_name": "Helvetia IT Services",
        "title": "IT Helpdesk Specialist",
        "description": "Support internal users. Hybrid work in Zürich. German B2 required. English fluent. 80% workload.",
        "remote": False,
        "url": "https://example.com/apply/1",
        "tags": ["helpdesk", "german", "zurich"],
        "job_types": ["full-time"],
        "location": "Zürich, Switzerland",
        "created_at": "2026-01-01",
    },
    {
        "_source_portal": "Datos demo",
        "slug": "mock-sysadmin-berlin",
        "company_name": "Berlin Cloud GmbH",
        "title": "Linux System Administrator",
        "description": "Remote-first across Germany. Cybersecurity awareness. Full-time 100%. English required.",
        "remote": True,
        "url": "https://example.com/apply/2",
        "tags": ["linux", "sysadmin", "remote"],
        "job_types": ["full-time"],
        "location": "Berlin, Germany",
        "created_at": "2026-01-02",
    },
    {
        "_source_portal": "Datos demo",
        "slug": "mock-security-vienna",
        "company_name": "AlpSec Austria",
        "title": "Junior Cybersecurity Analyst",
        "description": "On-site Vienna office. German C1. Part-time 50%. Hybrid possible after probation.",
        "remote": False,
        "url": "https://example.com/apply/3",
        "tags": ["security", "soc", "vienna"],
        "job_types": ["part-time"],
        "location": "Wien, Austria",
        "created_at": "2026-01-03",
    },
    {
        "_source_portal": "Datos demo",
        "slug": "mock-support-munich",
        "company_name": "Bayern Support AG",
        "title": "IT Support Engineer",
        "description": "Munich hybrid 60%. Administrative tasks plus ticketing. German B1+, English.",
        "remote": False,
        "url": "https://example.com/apply/4",
        "tags": ["it-support", "munich"],
        "job_types": ["full-time"],
        "location": "Munich, Germany",
        "created_at": "2026-01-04",
    },
    {
        "_source_portal": "Datos demo",
        "slug": "mock-admin-geneva",
        "company_name": "Geneva Pharma Ops",
        "title": "Administrative Coordinator IT",
        "description": "Geneva on-site. French/German office. 40% workload. English required.",
        "remote": False,
        "url": "https://example.com/apply/5",
        "tags": ["administrative", "geneva"],
        "job_types": ["part-time"],
        "location": "Geneva, Switzerland",
        "created_at": "2026-01-05",
    },
]
